[package]
name = "saitekswitch"
version = "1.1.0"
authors = ["Dave Attwood <git@attwoods.org.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.2.5"
xml-rs = "0.8"